### ISSUE TITLE
Can you suppress the Global title at the top of the page?

### ISSUE THREAD

**Issue by codazoda** [sutoiku/jsdox#90]
Wondering if there is a way to suppress the "Global" section at the top. I'm generating documentation for a single class and I think the global space is pretty well assumed.

**Comment by vdeturckheim** [comment]
There is an option to pass your own templates to jsdox. You can copy the built in ones and modify them before use.

**Comment by psq** [comment]
yes, indeed copy the `template` directory (https://github.com/sutoiku/jsdox/tree/master/templates), and then run `jsdoc` wtih `--templateDir new_dir`.

**Comment by codazoda** [comment]
After looking at the templates I realized that I was missing the module name, which resulted in "Global" appearing there instead. I added the following to the docblock for my class definition and the documentation looks more like I would expect it to.

```
@module MyModuleName
```
