### ISSUE TITLE
Jsdox doesn't handle optional parameters

### ISSUE THREAD

**Issue by scriptype** [sutoiku/jsdox#91]
I use optional parameter syntax in my jsdoc like:
```
@param {String} [foo] - Does foo
```
which is explained at http://usejsdoc.org/tags-param.html#optional-parameters-and-default-values

Jsdox, however, doesn't seem to stylise these optional parameters. Am I missing something?

**Comment by psq** [comment]
it shouldn't treat it any differently with the current template than any other parameter.

Look at this example: https://github.com/sutoiku/jsdox/blob/master/fixtures/test4.js#L36

which gets translated to: https://github.com/sutoiku/jsdox/blob/master/sample_output/test4.md

what were you expecting?

**Comment by scriptype** [comment]
Hi @psq if I write a jsdoc comment like:
```
/**
 * Create relation between two assets
 * @method createRelation
 * @param target1Id {String} - ID of first asset
 * @param target2Id {String} - ID of second asset
 * @param relationType {String} - Type of relation e.g: 'related'
 * @param [metadata] {Object} - Optional metadata fields to write to relation node
 * @returns {Promise}
 */
```

original jsdoc outputs (in default theme):
![screen shot 2016-02-09 at 23 44 11](https://cloud.githubusercontent.com/assets/5516876/12931611/534b74ea-cf87-11e5-9bbd-58254b4dc05d.png)

You can see there are 2 references stating the `metadata` parameter is optional.

I was expecting to see a similar result with jsdox.

I've seen the links you shared, but in those examples it looks like author just has named those parameters `optional`. And despite the brackets around it, parameter looks no different. If there are templates other than this default one, which takes this subject seriously, I'd like to give them a shot.

**Comment by psq** [comment]
the default template does not differentiate.  But if you run with `--debug`, you get this output for the parameters:
```
   params: 
     [ { type: { names: [ 'String' ] },
         description: 'filename to parse',
         name: 'file' },
       { type: { names: [ 'Boolean' ] },
         optional: true,
         description: 'Changes behavior',
         name: 'optional' } ]
```

so the data is available and you should be able to make your own template and style it based on the value of the `optional` attribute.

**Comment by scriptype** [comment]
:disappointed: 

![296](https://cloud.githubusercontent.com/assets/5516876/12934100/dadb8c58-cf94-11e5-8d93-a4ac73f5895d.jpg)
